# 张量 (Tensor)
**张量**其实是一种类似于矩阵和数组的的数据结构。在 [PyTorch](https://pytorch.org/) 中，在很多地方我们都会使用到张量，例如我们会用张量去存储一个模型的输入和输出，除此之外，我们也会将模型的参数用张量的形式存储下来。

张量和 [Numpy](https://numpy.org/) 中的 ndarrays 非常类似，最主要的不同之处就是我们可以利用很多特殊的硬件，例如 GPU，来加速张量的运算。同时，Numpy 的 ndarrays 可以做到和 PyTorch 中的张量做到无缝快速转换，因为他们使用的是同一份内存，无需耗时的拷贝。除此之外，相较于 ndarray，PyTorch 中的张量实现了自动求导特性（后面我们会详细讲述）。其实，只要你以前接触过 Numpy 的 ndarray，PyTorch 中的张量便可以快速上手。


In [21]:
import torch
import numpy

## 创建张量

**利用数组进行创建**

In [22]:
data = [[1, 2], [3, 4]]
data_tensor = torch.tensor(data)
print(data_tensor)

tensor([[1, 2],
        [3, 4]])


**利用 Numpy ndarray 进行创建**

In [3]:
data = [[1, 2], [3, 4]]
data_numpy = numpy.array(data)
data_tensor = torch.from_numpy(data_numpy)
print(data_tensor)

tensor([[1, 2],
        [3, 4]])


**利用其它 Tensor 进行创建**

In [23]:
data = [[1, 2], [3, 4]]
data_tensor = torch.tensor(data)
print(f"data_tensor is {data_tensor}")
ones_tensor = torch.ones_like(data_tensor)
print(f"ones_tensor is {ones_tensor}")
random_tensor = torch.rand_like(data_tensor, dtype=torch.float)
print(f"random_tensor is {random_tensor}")

data_tensor is tensor([[1, 2],
        [3, 4]])
ones_tensor is tensor([[1, 1],
        [1, 1]])
random_tensor is tensor([[0.6136, 0.9046],
        [0.8592, 0.9953]])


**指定形状进行创建**

In [24]:
shape = (3,2,)
random_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"random_tensor is {random_tensor}")
print(f"ones_tensor is {ones_tensor}")
print(f"zeros_tensor is {zeros_tensor}")

random_tensor is tensor([[0.8660, 0.8976],
        [0.9659, 0.6104],
        [0.7552, 0.8644]])
ones_tensor is tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
zeros_tensor is tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


## Tensor 的特性

Tensor 拥有许多属性，例如形状，数据类型，和位于的硬件

In [6]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## 对 Tensor 进行操作

PyTorch 的 Tensor 支持上百种操作，例如算术运算，矩阵运算等。每种运算既可以在 CPU 上进行，也可以在 GPU 上进行。默认情况下，Tensor 位于 CPU 上，其进行的各种运算操作也是在 CPU 上。

In [7]:
tensor = torch.rand(3,4)
print(f"{tensor.device}")
tensor = tensor.to('cuda')
print(f"{tensor.device}")

cpu
cuda:0


索引和分片操作

In [25]:
tensor = torch.ones(4, 4)
print('First row: ', tensor[0])
print('First column: ', tensor[:, 0])
print('Last column:', tensor[:, -1])
tensor[:,1] = 0
print(tensor)

First row:  tensor([1., 1., 1., 1.])
First column:  tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


拼接张量

In [26]:
print(f'Shape of tensor before concatenation: {tensor.shape}')
cat_tensor = torch.cat([tensor, tensor, tensor], dim=1)
print(f'Shape of tensor after concatenation: {cat_tensor.shape}')

Shape of tensor before concatenation: torch.Size([4, 4])
Shape of tensor after concatenation: torch.Size([4, 12])


运算操作

In [27]:
# This computes the matrix multiplication between two tensors. y1, y2, y3 will have the same value
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)


# This computes the element-wise product. z1, z2, z3 will have the same value
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

只有一个元素的张量可以直接转化为 Python 的数值类型

In [28]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

12.0 <class 'float'>


对张量进行 in-place 操作

In [29]:
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


## 和 Numpy 的联系

张量转换为 Numpy ndarray

In [30]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


改变张量也将改变 Numpy ndarray

In [31]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


Numpy ndarray 转换为张量

In [32]:
n = numpy.ones(5)
t = torch.from_numpy(n)

改变 Numpy ndarray 也将改变张量


In [33]:
numpy.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
